language: python
python:
  - "2.7"
# command to install dependencies
install: 
 - pip install -r requirements.txt
 - pip install coveralls
# add necessary environment variable
env: ARENBERG_ONLINE_DJANGO_SECRET_KEY=dummy
# command to run tests
script:
  coverage run --source=arenberg-online,core,ticketing manage.py test
# compute fraction of code that is automatically tested
after_success:
  coveralls
