# Configuration file for Travis CI.
# Makes all tests run automatically on each commit.
language: python
python:
  - "2.7"
# Install dependencies.
install: 
 - pip install -r requirements.txt
 - pip install coveralls
# Prepare the build for testing.
# (Simulate the effects of cloning the arenberg-secure repo.)
before_script:
 - mkdir arenberg-secure
 - echo "dummykey" > arenberg-secure/django_secret_key.txt
# Run tests.
script:
  coverage run --source=arenberg-online,core,ticketing --omit=*/tests.py manage.py test
# Compute fraction of code that is automatically tested.
after_success:
  coveralls
