given_paper_tickets = {
	'23 for do': (
		('Ine', 'Decuypere', 2),
		('Joanna', 'Houlleberghs', 2),
		('Nele', 'Rober', 2),
		('Joachim', 'Vermunicht', 4),
		('Anne', 'Van Gemert', 5),
		('Ellen', 'Van Caillie', 5),
		('Irene', 'Maes', 5),
		('Laurine', 'Peeters', 5),
		('Laurine', 'Philippe', 5),
		('Maarten', 'Van den Broeck', 5),
		('Olesya', 'Didukh', 5),
		('Jonathan', 'Vermunicht', 6),
		('Tine', 'Drees', 6),
		('Xing', 'Gao', 6),
		('Axelle', 'Gysemans', 7),
		('Caroline', 'Jansen', 7),
		('Wouter', 'Vannoppen', 7),
		('Dorus', 'Vleer', 8),
		('Ine', 'Rens', 8),
		('Marijn', 'Van Bedaf', 8),
		('Andreas', 'De Preter', 10),
		('Jaana', 'Van den Bossche', 10),
		('Lennert', 'Ovaere', 10),
		('Lieselot', 'smolders', 10),
		('Lucie', 'Moens', 10),
		('Oscar', 'Volger', 10),
		('Ruben', 'Vroonen', 10),
		('Thomas', 'Van Ryckeghem', 10),
	),
	'23 for vr': (
		('Ine', 'Decuypere', 3),
		('Xing', 'Gao', 4),
		('Lise', "D'Hoop", 4),
		('Anne', 'Van Gemert', 5),
		('Ellen', 'Van Caillie', 5),
		('Laurine', 'Philippe', 5),
		('Olesya', 'Didukh', 5),
		('Caroline', 'Jansen', 5),
		('Ine', 'Rens', 5),
		('Lieselot', 'smolders', 5),
		('Nele', 'Rober', 6),
		('Tine', 'Drees', 6),
		('Wouter', 'Vannoppen', 7),
		('Hannah', 'Lewyllie', 7),
		('Laurine', 'Peeters', 10),
		('Andreas', 'De Preter', 10),
		('Lennert', 'Ovaere', 10),
		('Lucie', 'Moens', 10),
		('Oscar', 'Volger', 10),
		('Ruben', 'Vroonen', 10),
		('Thomas', 'Van Ryckeghem', 10),
	),
	'30 for do': (
		('Laura', 'Verbert', 1),
		('Cara', 'Coffyn', 2),
		('Joachim', 'Vermunicht', 2),
		('Liesa', 'Daelemans', 2),
		('Lisa', 'Rooijakkers', 2),
		('Margot', 'De Vis', 2),
		('Floor', 'Vermeer', 3),
		('Lise', "D'Hoop", 3),
		('Lucie', 'Moens', 3),
		('Muriel', 'Macken', 4),
		('Hannelore', 'Van Gool', 5),
		('Katelijne', 'Bikkembergs', 5),
		('Lore', 'Vrebos', 5),
		('Marijn', 'Van Bedaf', 5),
		('Yixin', 'Cai', 8),
		('Nele', 'Rober', 9),
		('Joren', 'Vandeperre', 10),
		('Xing', 'Gao', 10),
	),
	'30 for vr': (
		('Lise', "D'Hoop", 1),
		('Nele', 'Rober', 2),
		('Floor', 'Vermeer', 3),
		('Lisa', 'Rooijakkers', 4),
		('Charlotte', 'Janssens', 4),
		('Muriel', 'Macken', 5),
		('Hannelore', 'Van Gool', 5),
		('Katelijne', 'Bikkembergs', 5),
		('Yixin', 'Cai', 6),
		('Joren', 'Vandeperre', 7),
		('Ellen', 'Van Caillie', 14),
		('Lore', 'Vrebos', 15),
	),
}